In [1]:
import sys
sys.path.append("..")  # para importar desde src/
from src.analysis import cargar_datos, limpiar_datos, ranking, resumen_hpe

df_raw = cargar_datos()
df = limpiar_datos(df_raw)
df

,Ticker,Empresa,Market Cap,P/E Ratio,P/E Forward,P/B Ratio,EV/EBITDA,Margen Neto,Margen Bruto,Margen Operativo,ROE,ROA,Crecimiento Ingresos,Ingresos Totales,Deuda/Capital,Razón Corriente
0,HPE,Hewlett Packard Enterprise Comp,83.55,32.44,13.69,3.15,14.18,6.67,36.62,12.56,10.94,2.64,33.7,41.87,76.46,1.11
1,DELL,Dell Technologies Inc.,357.89,32.78,19.33,-252.42,21.53,7.52,19.91,12.02,NaN,8.64,57.7,151.20,NaN,0.96
2,IBM,International Business Machines,212.46,20.05,17.15,6.17,16.37,15.52,58.10,16.55,34.46,5.30,1.1,69.09,188.97,0.79
3,CSCO,"Cisco Systems, Inc.",420.67,32.04,18.98,8.37,23.38,20.95,64.52,27.72,27.32,7.98,17.6,63.32,62.02,0.93
4,NTAP,"NetApp, Inc.",39.51,28.41,18.09,26.37,18.36,19.18,70.63,26.67,114.82,11.66,29.9,7.39,169.50,1.24

In [2]:

# Celda 2 — ¿Quién tiene mejor margen neto?
ranking(df, "Margen Neto")

                           Empresa Ticker  Margen Neto
0              Cisco Systems, Inc.   CSCO        20.95
1                     NetApp, Inc.   NTAP        19.18
2  International Business Machines    IBM        15.52
3           Dell Technologies Inc.   DELL         7.52
4  Hewlett Packard Enterprise Comp    HPE         6.67

In [3]:
# Celda 3 — ¿Cómo está HPE vs el promedio?
resumen_hpe(df)

                        HPE  Promedio Competidores
Market Cap            83.55                 222.82
P/E Ratio             32.44                  29.14
P/E Forward           13.69                  17.45
P/B Ratio              3.15                 -41.67
EV/EBITDA             14.18                  18.76
Margen Neto            6.67                  13.97
Margen Bruto          36.62                  49.96
Margen Operativo      12.56                  19.10
ROE                   10.94                  46.88
ROA                    2.64                   7.24
Crecimiento Ingresos   33.7                  28.00
Ingresos Totales      41.87                  66.57
Deuda/Capital         76.46                 124.24
Razón Corriente        1.11                   1.01